#!/usr/bin/env python

from waflib.Task import Task
from waflib.TaskGen import extension
import os

APPNAME = 'ocpf'
VERSION = '1.0'

def options(ctx):
    ctx.load('compiler_c flex bison')

def configure(ctx):
    ctx.load('compiler_c flex bison')

def build(bld):
    return
