[
	version(0.1),
	helpstring("Open MAPI Session")
] interface IMAPISession
{
  typedef [public, enum8bit] enum
	{
		op_MAPI_RPC_LOGON = 0xFE
	} mapi_opcodes;

	/************************* CALLS **********************************/
	typedef struct {
		uint8	col;
		uint8	row;
		uint32	locale_id;
		uint32	padding;
		[value(strlen(profile_info) + 1)] uint16 profile_info_length;
		[charset(DOS),string] uint8 profile_info[];
	} MAPI_RPC_LOGON_req;

	typedef struct {

	} MAPI_RPC_LOGON_repl;

	/***************************** UNIONS *****************************/
	typedef union {
		[case(op_MAPI_RPC_LOGON)] MAPI_RPC_LOGON_req mapi_rpc_logon;
	} MAPI_REQ_UNION;

	typedef union {
		[case(op_MAPI_RPC_LOGON)] MAPI_RPC_LOGON_repl mapi_rpc_logon;
	} MAPI_REPL_UNION;

	typedef [public] struct
	{
		uint8 opcode;
		uint8 action;
		[switch_is(opcode)] MAPI_REQ_UNION u;
	} MAPI_REQ;

	typedef [public] struct
	{
		uint8 opcode;
		uint8 action;
		[switch_is(opcode)] MAPI_REPL_UNION u;
	} MAPI_REPL;
}
