#define TDR_PAHEX TDR_PRINT_ARRAY_HEX

[
	version(0.1),
	helpstring("MAPI EcDoRpc operations")
] interface MAPI
{

  typedef [public, enum8bit, flag(TDR_PAHEX)] enum
	{
		op_MAPI_SETCOLUMNS = 0x12,
		op_MAPI_QUERYROWS = 0x15,
		op_MAPI_GET_RECEIVEFOLDER = 0x27,
		op_MAPI_GET_RECEIVEFOLDER_TABLE = 0x68,
		op_MAPI_OPEN_MSGSTORE = 0xFE
	} mapi_opcodes;

	/************************* CALLS **********************************/

	/* 0x12 setcolumns */

	typedef struct {
		uint8				handle;
		uint8				unknown;
		uint16				prop_nb;
		uint32				properties[prop_nb];
	} MAPI_SETCOLUMNS_req;

	/* 0xFE rpc logon */

	typedef struct {
		uint8	col;
		uint8	row;
		uint32	locale_id;
		uint32	padding;
		[value(strlen(profile_info) + 1)] uint16 profile_info_length;
		[charset(DOS), string] uint8 profile_info[-1];
	} MAPI_OPEN_MSGSTORE_req;


	typedef struct {
		uint32 dwLowDateTime;
		uint32 dwHighDateTime;
	} MAPI_FILETIME;

	typedef struct {
		uint8 ab[16];
	} MAPI_MAPIUID;

	typedef struct {
		uint8				cb;
		uint8				lpb[cb];
	} MAPI_SBinary;

	typedef struct {
		uint32	unknown;
		uint8   unknown2;
		hyper	folder_id[13];
		uint8	unknown3;
		MAPI_MAPIUID	pt_entryid;
		MAPI_SBinary	default_store;
		MAPI_MAPIUID	msgstore_guid;
		/* should be:		NTTIME	last_access; */
		MAPI_FILETIME ts_access;
		[charset(DOS), string] uint8 creation_date[-1];
		uint8	terminator;
	} MAPI_OPEN_MSGSTORE_repl;

	/***************************** UNIONS *****************************/
	typedef [public] union {
		[case(op_MAPI_SETCOLUMNS)] MAPI_SETCOLUMNS_req mapi_setcolumns;
		[case(op_MAPI_OPEN_MSGSTORE)] MAPI_OPEN_MSGSTORE_req mapi_open_msgstore;
	} MAPI_REQ_UNION;

	typedef [public] union {
		[case(op_MAPI_OPEN_MSGSTORE)] MAPI_OPEN_MSGSTORE_repl mapi_open_msgstore;
	} MAPI_REPL_UNION;

	typedef [public] struct
	{
		mapi_opcodes opcode;
		uint8 mapi_flags;
		[switch_is(opcode)] MAPI_REQ_UNION u;
	} MAPI_REQ;

	typedef [public] struct
	{
		mapi_opcodes opcode;
		uint8 mapi_flags;
		[switch_is(opcode)] MAPI_REPL_UNION u;
	} MAPI_REPL;
}
