/* Auto-generated by ./libmapi/conf/mparse.pl */


#include "openchange.h"
#include "libmapi/include/mapidefs.h"
#include "mapitags.h"


const char	*tag_to_x500[256][256][30] = {
	{
		{0, 0, 0, "test1", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0, 0, 0, "test2", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "test3", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "test4", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0, 0, 0, "test5", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "test6", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "test7", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
	},
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{ {0} },
	{
		{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "test42", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
	},
	{ {0} }
};

uint16_t	tab_index[256] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 7, 8, 9, 10, 11, 12, 13, 14, 0, 0, 15, 16, 17, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 21, 22, 23, 24, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 27, 0, 28, 29, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 34
};

uint16_t get_type_index(uint16_t type)
{
	switch (type) {
	case PT_UNSPECIFIED :
	case PT_NULL :
	case PT_SHORT :
	case PT_LONG :
	case PT_FLOAT :
	case PT_DOUBLE :
	case PT_CURRENCY :
	case PT_APPTIME :
		return type;
	case PT_ERROR :
		return 8;
	case PT_BOOLEAN :
		return 9;
	case PT_OBJECT :
		return 10;
	case PT_I8 :
		return 11;
	case PT_STRING8 :
		return 12;
	case PT_UNICODE :
		return 13;
	case PT_SYSTIME :
		return 14;
	case PT_CLSID :
		return 15;
	case PT_BINARY :
		return 16;
	case PT_MV_SHORT :
		return 18;
	case PT_MV_LONG :
		return 19;
	case PT_MV_FLOAT :
		return 20;
	case PT_MV_DOUBLE :
		return 21;
	case PT_MV_CURRENCY :
		return 22;
	case PT_MV_APPTIME :
		return 23;
	case PT_MV_I8 :
		return 24;
	case PT_MV_STRING8 :
		return 25;
	case PT_MV_UNICODE :
		return 26;
	case PT_MV_SYSTIME :
		return 27;
	case PT_MV_CLSID :
		return 28;
	case PT_MV_BINARY :
		return 29;
	default :
		break;
	}

	return 0xFF;
}

uint8_t get_line_index(uint8_t line)
{
	return tab_index[line];
}

const char *get_ad_name(uint32_t mapitag)
{
	uint8_t		line;
	uint8_t		col;
	uint16_t	type;
	uint16_t	i;

	line = (mapitag >> 24) & 0xFF;
	col = (mapitag >> 16) & 0xFF;
	type = mapitag & 0xFFFF;

	if ((i = get_type_index(type)) != 0xFF) {
		line = get_line_index(line);
		return tag_to_x500[line][col][i];
	}

	return NULL;
}

