.\" OpenChange Project Libraries Man Pages
.\"
.\" This manpage is Copyright (C) 2007 Julien Kerihuel;
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the OpenChange and Samba4 libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Process this file with
.\" groff -man -Tascii ChangeProfilePassword.3
.\"
.TH CHANGEPROFILEPASSWORD 3 2007-04-23 "OpenChange libmapi 0.2" "OpenChange Programmer's Manual"
.SH NAME
ChangeProfilePassword \- Change the password of an existing MAPI profile
.SH SYNOPSIS
.nf
.B #include <libmapi/libmapi.h>
.sp
.BI "enum MAPISTATUS ChangeProfilePassword(const char *" profile ", const char *" old_password ", const char *" password ", uint32_t " flags ");"
.fi
.SH DESCRIPTION
This function change the password of the profile
.IR profile

.SH RETURN VALUE
The function returns
.BI MAPI_E_SUCCESS 
on success, otherwise -1. The last error can be retrieved using
.B GetLastError().
Possible MAPI error codes are:

.BR "MAPI_E_INVALID_PARAMETER":
One of the following argument was not set:
.IR profile,
.IR old_password,
.IR password

.BR "MAPI_E_NOT_FOUND": 
The profile was not found in the database

.SH "SEE ALSO"
.BR CreateProfile (3),
.BR ChangeProfilePassword (3),
.BR GetProfileTable (3),
.BR GetProfileAttr (3),
.BR ProcessNetworkProfile (3),
.BR GetLastError (3)

.SH NOTE
.IR flags
is currently unsupported and won't affect the function behavior.

.SH AUTHOR
Julien Kerihuel <j.kerihuel at openchange dot org>
