.\" OpenChange Project Libraries Man Pages
.\"
.\" This manpage is Copyright (C) 2007 Julien Kerihuel;
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the OpenChange and Samba4 libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Process this file with
.\" groff -man -Tascii GetProfileAttr.3
.\"
.TH GETPROFILEATTR 3 2007-04-23 "OpenChange libmapi 0.4" "OpenChange Programmer's Manual"
.SH NAME
GetProfileAttr \- Retrieve attribute values from a profile
.SH SYNOPSIS
.nf
.B #include <libmapi/libmapi.h>
.sp
.BI "enum MAPISTATUS GetProfileAttr(struct mapi_profile *" profile ", const char *" attribute ", unsigned int *" count ", char ***" value ");"
.fi
.SH DESCRIPTION
This function retrieves all the attribute values from the given 
.IR profile.
The number of results is stored in
.IR count
and values are stored in an allocated string array in the
.IR value 
parameter that needs to be free using
.IR MAPIFreeBuffer() .

.SH RETURN VALUE
The function returns
.BI MAPI_E_SUCCESS 
on success, otherwise value is set to
.B NULL
and the function returns -1. The last error can be retrieved using
.B GetLastError().
Possible MAPI error codes are:

.BI "MAPI_E_NOT_INITIALIZED:"
MAPI subsystem has not been initialized

.BI "MAPI_E_INVALID_PARAMETER:"
Either
.IR profile
or
.IR attribute
was not set properly

.BI "MAPI_E_NOT_FOUND:" 
The profile was not found in the database

.SH "SEE ALSO"
.BR SetDefaultProfile (3),
.BR GetDefaultProfile (3),
.BR GetProfileTable (3),
.BR GetLastError (3)

.SH AUTHOR
Julien Kerihuel <j.kerihuel at openchange dot org>
