.\" OpenChange Project Libraries Man Pages
.\"
.\" This manpage is Copyright (C) 2007 Julien Kerihuel;
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the OpenChange and Samba4 libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Process this file with
.\" groff -man -Tascii MAPILogonEx.3
.\"

.TH MAPILOGONEX 3 2007-06-01 "OpenChange libmapi 0.2" "OpenChange Programmer's Manual"
.SH NAME
MapiLogonEx \- Create a full MAPI Session
.SH SYNOPSIS
.nf
.B #include <libmapi/libmapi.h>
.sp
.BI "enum MAPISTATUS MapiLogonEx(struct mapi_session **" session ", const char *" profname ");"
.fi
.SH DESCRIPTION
This function opens the profile name set in
.IR profname 
and establish connections on Exchange related pipes using information
stored in this profile. The function set a valid MAPI session pointer in
.IR session 
on success.

.SH RETURN VALUE
The function returns
.BI MAPI_E_SUCCESS 
on success, otherwise -1. Developers should call
.B GetLastError()
to retrieve the latest MAPI error code. Possible MAPI error codes are:

.BR "MAPI_E_NOT_INITIALIZED":
MAPI subsystem has not been initialized

.BR "MAPI_E_NOT_ENOUGH_RESOURCES": 
MAPI subsystem failed to allocate the necessary resources to operate properly

.SH "SEE ALSO"
.BR MAPIInitialize (3),
.BR MAPILogonProvider (3),
.BR GetLastError (3)

.SH "AUTHOR"
Julien Kerihuel <j.kerihuel at openchange dot org>

