.\" OpenChange Project Libraries Man Pages
.\"
.\" This manpage is Copyright (C) 2007 Julien Kerihuel;
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the OpenChange and Samba4 libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Process this file with
.\" groff -man -Tascii mapi_object.3
.\"

.TH MAPI_OBJECT 3 2007-04-23 "OpenChange libmapi 0.2" "OpenChange Programmer's Manual"
.SH NAME
mapi_object API \- Manipulate generic MAPI objects
.SH SYNOPSIS
.nf
.B #include <libmapi/libmapi.h>
.sp
.BI "void mapi_object_init(mapi_object_t *" obj ");"
.BI "void mapi_object_release(mapi_object_t *" obj ");"
.BI "mapi_id_t mapi_object_get_id(mapi_object_t *" obj ");"
.BI "void mapi_object_debug(mapi_object_t *" obj ");"
.fi
.SH DESCRIPTION
These functions are used to manipulate mapi_object elements.
.sp
.B mapi_object_init
is called before any mapi object manipulation
.B mapi_object_release
is called when the object is not anymore necessary
.B mapi_object_get_id 
is used to retrieve an object mapi id
.B mapi_object_debug
is used to debug mapi objects
.fi

.SH AUTHOR
Julien Kerihuel <j.kerihuel at openchange dot org>
