.\" OpenChange Project Libraries Man Pages
.\"
.\" This manpage is Copyright (C) 2007 Julien Kerihuel;
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the OpenChange and Samba4 libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Process this file with
.\" groff -man -Tascii MonitorNotification.3
.\"
.TH MONITORNOTIFICATION 3 2007-06-01 "OpenChange libmapi 0.4" "OpenChange Programmer's Manual"
.SH NAME
MonitorNotification \- Wait for notifications and process them
.SH SYNOPSIS
.nf
.B #include <libmapi/libmapi.h>
.sp
.BI "enum MAPISTATUS MonitorNotification(void *" private_data ");"
.fi
.SH DESCRIPTION
This function indefinively waits for notifications on the UDP port and
generates the traffic needed to receive MAPI notifications. These MAPI
notifications are next compared to the registered ones and the callback specified in
.BI Subscribe()
called if it matches.  

Note that the function will loop indefinitively until an error occurs.

.SH RETURN VALUE
The function returns
.BI MAPI_E_SUCCESS 
on success, otherwise -1. Developers should call
.B GetLastError()
to retrieve the latest MAPI error code. Possible
MAPI error codes are:

.BR "MAPI_E_NOT_INITIALIZED": 
MAPI subsystem has not been initialized

.BR "MAPI_E_CALL_FAILED":
A network problem was encountered during the transaction

.SH "SEE ALSO"
.BR RegisterNotification (3),
.BR Subscribe (3),
.BR Unsubscribe(3),
.BR GetLastError (3)

.SH AUTHOR
Julien Kerihuel <j.kerihuel at openchange dot org>

.SH "BUGS"
This code is experimental. The current implementation is non-threaded,
only supports fnevNewmail and fnevCreatedObject notifications and will
block your process until you send a signal.
