/*
   OpenChange Storage Abstraction Layer library

   OpenChange Project

   Copyright (C) Julien Kerihuel 2015

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

cpp_quote("#include <util/debug.h>")
cpp_quote("#include <gen_ndr/ndr_misc.h>")

[
 pointer_default(unique)
]

/**
   Internal mapistore interface used to share information about
   session, subscription and notification data between emsmdb and
   asyncemsmdb ednpoints
 */

interface mapistore_notification
{
	typedef [enum8bit] enum {
		MAPISTORE_NOTIFICATION_V1	= 1
	} interface_vnum;

	/* session */
	typedef [public, flag(LIBNDR_FLAG_NOALIGN)] struct {
		GUID								uuid;
		[flag(LIBNDR_FLAG_STR_ASCII|LIBNDR_FLAG_STR_NULLTERM)] string	cn;
	} session_v1;

	typedef [public, flag(LIBNDR_FLAG_NOALIGN), nodiscriminant] union {
		[case(MAPISTORE_NOTIFICATION_V1)] session_v1 v1;
		[default];
	} session_ver;

	typedef [public, flag(LIBNDR_FLAG_NOALIGN)] struct {
		interface_vnum			vnum;
		[switch_is(vnum)] session_ver	v;
	} mapistore_notification_session;


	/* resolver */
	typedef [public, flag(LIBNDR_FLAG_NOALIGN)] struct {
		[range(0, 100000)] uint32 count;
		[size_is(count),flag(LIBNDR_FLAG_STR_ASCII|LIBNDR_FLAG_STR_NULLTERM)] string hosts[];
	} resolver_v1;

	typedef [public, flag(LIBNDR_FLAG_NOALIGN), nodiscriminant] union {
		[case(MAPISTORE_NOTIFICATION_V1)] resolver_v1 v1;
		[default];
	} resolver_ver;

	typedef [public, flag(LIBNDR_FLAG_NOALIGN)] struct {
		interface_vnum			vnum;
		[switch_is(vnum)] resolver_ver	v;
	} mapistore_notification_resolver;

}
