#!/usr/bin/env python

from waflib.Task import Task
from waflib.TaskGen import extension

APPNAME = 'mapipp'
VERSION = '1.0'

def options(ctx):
    ctx.load('g++')

def configure(ctx):
    ctx.recurse('../libmapi')
    ctx.load('g++')
    ctx.env.CPPFLAGS = ['-Wall', '-g3']

def build(bld):
    target = bld.shlib(
        features = 'c cshlib',
        source = [
            'src/attachment.cpp',
            'src/folder.cpp',
            'src/mapi_exception.cpp',
            'src/message.cpp',
            'src/object.cpp',
            'src/profile.cpp',
            'src/session.cpp'
            ],
        target = APPNAME,
        vnum = VERSION,
        includes = ['.', '../', 'build'],
        depends_on = 'libmapi',
        use = ['mapi'])
