INSERT company VALUES (1, 'zentyal-domain.lan');
INSERT organizational_units VALUES (1, 1, 'First Organization', 'First Administrative Group');
INSERT servers VALUES (1, 1, 1, 402);
INSERT public_folders VALUES (1, 1, 'c4898b91-da9d-4f3e-9ae4-8a8bd5051b89');
INSERT mailboxes VALUES (1, 1, 720575940379279361, 'paco', '13c54881-02f6-4ade-ba7d-8b28c5f638c6', 'd87292c1-1bc3-4370-a734-98b559b69a52', 1, 1, NULL);
INSERT mailboxes_properties VALUES (1, 'PidTagAccess', '63'), (1, 'PidTagCreationTime', '130268260180000000'),(1, 'PidTagFolderType', '1'),(1, 'PidTagLastModificationTime', '130268260180000000'),(1, 'PidTagRights', '2043'),(1, 'PidTagSubFolders', 'TRUE'),(1, 'PidTagMessageClass', 'IPC'),(1, 'PidTagIpmDraftsEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAABoAAA=='),(1, 'PidTagIpmAppointmentEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAABsAAA=='),(1, 'PidTagIpmContactEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAABwAAA=='),(1, 'PidTagIpmTaskEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAAB0AAA=='),(1, 'PidTagIpmNoteEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAAB4AAA=='),(1, 'PidTagIpmJournalEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAAB8AAA=='),(1, 'PidTagRemindersOnlineEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAABIAAA=='),(1, 'PidTagChangeNumber', '4683743612465315841');
INSERT INTO folders VALUES (0, 1, 1, 'publicfolder', NULL, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 2) as t), NULL, 1, NULL);
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Public Folder Root');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderChildCount', '2');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '72057594037927937');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagSubFolders', 'TRUE');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Public Folder Root');



INSERT INTO folders VALUES (0, 1, 1369094286720630785, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 720575940379279361) as t), 1, 10, NULL);
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'To-Do');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '2017612633061982209');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Task');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '2');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'To-Do');

INSERT INTO folders VALUES (0, 1, 1152921504606846977, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 720575940379279361) as t), 1, 7, 'sogo://paco@fallback/0x1000000000000001/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Views');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '1585267068834414593');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Views');

INSERT INTO folders VALUES (0, 1, 1297036692682702849, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 720575940379279361) as t), 1, 9, NULL);
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Reminders');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '1873497444986126337');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'Outlook.Reminder');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '2');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Reminders');

INSERT INTO folders VALUES (0, 1, 2377900603251621889, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 720575940379279361) as t), 1, NULL, 'sogo://paco@fallback/0x2100000000000001/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Freebusy Data');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '4971973988617027585');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '5044031582654955521');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Freebusy Data');

INSERT INTO folders VALUES (0, 1, 1008806316530991105, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 720575940379279361) as t), 1, 5, 'sogo://paco@fallback/0xe00000000000001/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Schedule');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '1297036692682702849');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Schedule');

INSERT INTO folders VALUES (0, 1, 864691128455135233, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 720575940379279361) as t), 1, 3, 'sogo://paco@fallback/0xc00000000000001/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Spooler Queue');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '1008806316530991105');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Spooler Queue');

INSERT INTO folders VALUES (0, 1, 792633534417207297, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 720575940379279361) as t), 1, 2, 'sogo://paco@fallback/0xb00000000000001/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Deferred Action');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '864691128455135233');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Deferred Action');

INSERT INTO folders VALUES (0, 1, 1513209474796486657, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 720575940379279361) as t), 1, 12, NULL);
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Top of Information Store');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '2305843009213693953');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagSubfolders', 'TRUE');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Top of Information Store');

INSERT INTO folders VALUES (0, 1, 1585267068834414593, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, 13, 'sogo://paco:paco@mail/folderINBOX/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagIpmContactEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAABwAAA==');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRemindersOnlineEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAABIAAA==');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagIpmJournalEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAAB8AAA==');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagIpmAppointmentEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAABsAAA==');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'INBOX');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '4755801206503243777');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagIpmDraftsEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAABoAAA==');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagIpmTaskEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAAB0AAA==');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagIpmNoteEntryId', 'AAAAAIFIxRP2At5Kun2LKMX2OMYBAMGSctjDG3BDpzSYtVm2mlIAAAAAAB4AAA==');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagMessageClass', 'All');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagMessageClass', 'IPM');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagMessageClass', 'Report.IPM');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'INBOX');

INSERT INTO folders VALUES (0, 1, 11961560610296037377, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, NULL, 'sogo://paco:paco@mail/folderFUCK/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'FUCK');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130282261650000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '14843864371813154817');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130282261650000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'FUCK');

INSERT INTO folders VALUES (0, 1, 1080863910568919041, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 720575940379279361) as t), 1, 6, 'sogo://paco@fallback/0xf00000000000001/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Finder');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '1441151880758558721');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Finder');

INSERT INTO folders VALUES (0, 1, 3, 'publicfolder', NULL, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1) as t), 1, 3, NULL);
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'NON_IPM_SUBTREE');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderChildCount', '4');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '216172782113783809');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note (check this)');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagSubFolders', 'TRUE');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'NON_IPM_SUBTREE');

INSERT INTO folders VALUES (0, 1, 2161727821137838081, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, 4, 'sogo://paco@notes/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.StickyNote');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Notes');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '4179340454199820289');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Notes');

INSERT INTO folders VALUES (0, 1, 4, 'publicfolder', NULL, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 3) as t), 1, -1, NULL);
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Events Root');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderChildCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '648518346341351425');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note (check this)');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagSubFolders', 'FALSE');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Events Root');

INSERT INTO folders VALUES (0, 1, 5, 'publicfolder', NULL, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 3) as t), 1, 4, NULL);
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'EFORMS REGISTRY');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderChildCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '288230376151711745');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note (check this)');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagSubFolders', 'FALSE');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'EFORMS REGISTRY');

INSERT INTO folders VALUES (0, 1, 936748722493063169, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 720575940379279361) as t), 1, 4, 'sogo://paco@fallback/0xd00000000000001/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Common Views');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '1152921504606846977');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Common Views');

INSERT INTO folders VALUES (0, 1, 2017612633061982209, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, 2, 'sogo://paco@contacts/personal/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Contact');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Personal Address Book');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '3602879701896396801');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Personal Address Book');

INSERT INTO folders VALUES (0, 1, 6, 'publicfolder', NULL, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1) as t), 1, 2, NULL);
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'IPM_SUBTREE');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderChildCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '144115188075855873');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note (check this)');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagSubFolders', 'FALSE');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'IPM_SUBTREE');

INSERT INTO folders VALUES (0, 1, 1224979098644774913, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 720575940379279361) as t), 1, 8, 'sogo://paco@fallback/0x1100000000000001/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Shortcuts');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '1729382256910270465');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Shortcuts');

INSERT INTO folders VALUES (0, 1, 1441151880758558721, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 720575940379279361) as t), 1, 11, NULL);
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Tracked Mail Processing');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '2161727821137838081');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '2');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Tracked Mail Processing');

INSERT INTO folders VALUES (0, 1, 2089670227099910145, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, 3, 'sogo://paco@tasks/personal/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Task');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Personal Calendar (t)');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '3891110078048108545');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Personal Calendar (t)');

INSERT INTO folders VALUES (0, 1, 15852670688344145921, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, NULL, 'sogo://paco:paco@mail/folderA3/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'A3');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130282287560000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '576742227280134145');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130282287560000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'A3');

INSERT INTO folders VALUES (0, 1, 1657324662872342529, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, 14, 'sogo://paco:paco@outbox/folderDrafts/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Outbox');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '2594073385365405697');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Outbox');

INSERT INTO folders VALUES (0, 1, 15708555500268290049, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, NULL, 'sogo://paco:paco@mail/folderA1/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'A1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130282287560000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '288511851128422401');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130282287560000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'A1');

INSERT INTO folders VALUES (0, 1, 2233785415175766017, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, 5, 'sogo://paco@fallback/0x1f00000000000001/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Journal');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Journal');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '4467570830351532033');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Journal');

INSERT INTO folders VALUES (0, 1, 1801439850948198401, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, 16, 'sogo://paco@fallback/0x1900000000000001/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Deleted Items');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '2882303761517117441');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Deleted Items');

INSERT INTO folders VALUES (0, 1, 15780613094306217985, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, NULL, 'sogo://paco:paco@mail/folderA2/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'A2');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130282287560000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '432627039204278273');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130282287560000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'A2');

INSERT INTO folders VALUES (0, 1, 1729382256910270465, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, 15, 'sogo://paco:paco@mail/folderSent/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Sent');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '2738188573441261569');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Sent');

INSERT INTO folders VALUES (0, 1, 2305843009213693953, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, NULL, 'sogo://paco:paco@mail/folderSpam/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Spam');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '4899916394579099649');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Spam');

INSERT INTO folders VALUES (0, 1, 1873497444986126337, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, 0, 'sogo://paco:paco@mail/folderDrafts/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Drafts');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '3026418949592973313');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Drafts');

INSERT INTO folders VALUES (0, 1, 7, 'publicfolder', NULL, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 3) as t), 1, 5, NULL);
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'SCHEDULE+ FREE BUSY');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderChildCount', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '504403158265495553');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note (check this)');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagSubFolders', 'TRUE');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'SCHEDULE+ FREE BUSY');

INSERT INTO folders VALUES (0, 1, 1945555039024054273, 'systemfolder', 1, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1513209474796486657) as t), 1, 1, 'sogo://paco@calendar/personal/');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Appointment');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagRights', '2043');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130268260180000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentUnreadCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContentCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAccess', '63');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'Personal Calendar (c)');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '3314649325744685057');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderType', '1');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'Personal Calendar (c)');

INSERT INTO folders VALUES (0, 1, 8, 'publicfolder', NULL, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 3) as t), 1, 6, NULL);
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'OFFLINE ADDRESS BOOK');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderChildCount', '1');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '360287970189639681');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note (check this)');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagSubFolders', 'TRUE');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'OFFLINE ADDRESS BOOK');

INSERT INTO folders VALUES (0, 1, 9, 'publicfolder', NULL, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 7) as t), 1, 8, NULL);
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', 'EX:/o=first organization/ou=first administrative group');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderChildCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '576460752303423489');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note (check this)');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagSubFolders', 'FALSE');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', 'EX:/o=first organization/ou=first administrative group');

INSERT INTO folders VALUES (0, 1, 10, 'publicfolder', NULL, (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 8) as t), 1, 9, NULL);
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagDisplayName', '/o=First Organization/cn=addrlists/cn=oabs/cn=Default Offline Address Book');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeHidden', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagFolderChildCount', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagCreationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagChangeNumber', '432345564227567617');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeReadOnly', '0');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagContainerClass', 'IPF.Note (check this)');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagLastModificationTime', '130264095410000000');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagSubFolders', 'FALSE');
INSERT folders_properties VALUES (LAST_INSERT_ID(), 'PidTagAttributeSystem', '0');
INSERT folders_names VALUES (LAST_INSERT_ID(), 'en_US', '/o=First Organization/cn=addrlists/cn=oabs/cn=Default Offline Address Book');

INSERT INTO messages VALUES (0, 1, 2522015791327477762, 'systemMessage', (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 1873497444986126337) as t), 1, 'Sample message on system folder');
INSERT messages_properties VALUES (LAST_INSERT_ID(), 'PidTagHasNamedProperties', '0');

INSERT INTO messages VALUES (0, 1, 2522015791327477761, 'systemMessage', (SELECT id FROM (SELECT id FROM folders WHERE folder_id = 9) as t), 1, 'USER-/CN=RECIPIENTS/CN=PACO');
INSERT messages_properties VALUES (LAST_INSERT_ID(), 'PidTagHasNamedProperties', '0');

