#!/usr/bin/python
# OpenChange provision script
#
# Copyright (C) Jelmer Vernooij <jelmer@openchange.org> 2008
#   
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#   
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#   
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
sys.path.append("scripting/python")

import optparse
import samba.getopt as options
from samba.samdb import SamDB
from samba.auth import system_session
from openchange.provision import newuser

parser = optparse.OptionParser("oc_newuser [options] <username>")

sambaopts = options.SambaOptions(parser)
parser.add_option_group(sambaopts)

credopts = options.CredentialsOptions(parser)
parser.add_option_group(credopts)

opts, args = parser.parse_args()

if len(args) == 0:
	parser.print_usage()
	sys.exit(1)

lp = sambaopts.get_loadparm()
creds = credopts.get_credentials(lp)

samdb = SamDB(url=lp.get("sam database"), session_info=system_session(), 
              credentials=creds, lp=lp)

newuser(samdb, lp, args[0])
