#!/usr/bin/python
# OpenChange provision script
#
# Copyright (C) Jelmer Vernooij <jelmer@openchange.org> 2008
#   
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#   
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#   
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import optparse
import os,sys

# To allow running from the source directory
sys.path.append("python")

from openchange import find_samba_python_path
samba_path = find_samba_python_path()
if samba_path is not None:
	sys.path.append(samba_path)

import samba
import samba.getopt as options
from samba.auth import system_session
import openchange.provision as openchange

parser = optparse.OptionParser("openchange_newuser [options] <username>")

sambaopts = options.SambaOptions(parser)
parser.add_option_group(sambaopts)

credopts = options.CredentialsOptions(parser)
parser.add_option_group(credopts)
parser.add_option("--enable", action="store_true", metavar="ENABLE",
		  help="Enable access to OpenChange server")
parser.add_option("--disable", action="store_true", metavar="DISABLE",
		  help="Disable access to OpenChange server")
parser.add_option("--create", action="store_true", metavar="CREATE",
		  help="Create the OpenChange user account")
parser.add_option("--mailbox", action="store_true", metavar="MAILBOX",
		  help="Create the OpenChange user mailbox")

opts, args = parser.parse_args()

if len(args) == 0:
	parser.print_usage()
	sys.exit(1)

lp = sambaopts.get_loadparm()
creds = credopts.get_credentials(lp)

def setup_path(*args):
	return os.path.join(os.path.dirname(__file__), *args)

if opts.enable == True:
	openchange.accountcontrol(lp, creds, username=args[0], value=0)

if opts.disable == True:
	openchange.accountcontrol(lp, creds, username=args[0], value=2)

if opts.create == True:
	openchange.newuser(lp, creds, username=args[0])

if opts.mailbox == True:
	openchange.newmailbox(lp, username=args[0], firstorg=None, firstou=None)
